### ISSUE TITLE
I want to put the year before month, how to do?

### ISSUE THREAD

**Issue by chairy11** [Nerian/bootstrap-datepicker-rails#102]
Hi, I'm Chinese, and use this gem in language Zh-CN.
![untitled 13](https://cloud.githubusercontent.com/assets/1669457/7601998/ea92b736-f950-11e4-9ff0-6506d9e05700.png)

Look at the image, there is something uncomfortable for us Chinese, that we would like it show"2015年5月". 
Can you tell me how to customize the view in the rails 4 when using this gem?
Thank you very much : )

**Comment by Nerian** [comment]
Hi,

I don't know how to customize that bit. You may want to ask in the original project: https://github.com/eternicode/bootstrap-datepicker

**Comment by svavantsa** [comment]
Have you seen the documentation? It is available here.
http://bootstrap-datepicker.readthedocs.org/en/latest/

This is just for English. Even here it doesn't talk about how to arrange
the month/year header. Most of the customization is only for how the date
appears after it is selected.

In any case, can someone point it out for other languages?
ᐧ


Thank You,

Surya Avantsa

How do they say my name? <http://vame.me/suryaavantsa>
