### ISSUE TITLE
Start/End Dates fail to set with a year format

### ISSUE THREAD

**Issue by Phillita** [Nerian/bootstrap-datepicker-rails#105]
Hello,
I was trying to make a year picker using this but it turns out that if I change the output format of the date, it no longer is able to set the Start and End dates. Using any sort of formatted date seems to fail but using `-30y` and `-1d` as the start and end date seems to work.

![screen shot 2015-08-11 at 9 23 47 am](https://cloud.githubusercontent.com/assets/1016928/9198533/b8cc7be6-400a-11e5-9dbb-6c25f97d9fe1.png)
![screen shot 2015-08-11 at 9 44 13 am](https://cloud.githubusercontent.com/assets/1016928/9198940/904d4850-400d-11e5-987d-78dca842c4b0.png)

**Comment by Nerian** [comment]
Hi,

Not sure how to do this. You may want to ask in the actual project repo: https://github.com/eternicode/bootstrap-datepicker.

But wouldn't it be better to use rails' built in year picker?

**Comment by Phillita** [comment]
Good suggestion actually! I took a quick look and it doesn't seem that I am able to split the rails year picker from the rest of the date selections. 

I can however send this over to the actual repo and see where this goes.

**Comment by Phillita** [comment]
Good suggestion! I looked into the select_year and it works pretty well, it just doesn't have the nice interface. I should move this issue over to the other repo though.

**Comment by Phillita** [comment]
If anyone else is interested, I found an issue that is one in the same:
https://github.com/eternicode/bootstrap-datepicker/issues/967
