### ISSUE TITLE
Turbolinks seems to mess things up

### ISSUE THREAD

**Issue by ghost** [Nerian/bootstrap-datepicker-rails#106]
I have turbolinks enabled (at least for now) and everything works fine from a regular page load, but if I come from another page, the calendar does show up, but when I click outside of the calendar to close it down the value of the field becomes blank again. I don’t know if anyone else is having that issue. I probably should just not use turbolinks, it’s my first time trying it out.

**Comment by hydrozen** [comment]
It only seems to happen if autoclose is set to false. Changing autoclose to true fixes the problem. Weird.

**Comment by svavantsa** [comment]
I still don't understand why you are suspecting turbolinks.

Surya Avantsa

**Comment by hydrozen** [comment]
I suspect turbolinks because I only get the problem if I navigated from another page (using turbolinks). If I load the page with the date picker directly (thus this was a normal request, not an xhr), I don’t have the issue.

**Comment by Nerian** [comment]
Have you set up the initializer like this?

```
$(document).on('page:change', function(){
 $('.datepicker').datepicker();
});


```

**Comment by hydrozen** [comment]
No I’m initializing it using the data attributes. Maybe that’s the problem... but the datapicker does show up though, it just doesn’t behave nice when you select a date and then click outside of it.

**Comment by wellington1993** [comment]
Eu tenho o mesmo problema. Depois de clicar fora do input o valor do mesmo desaparece.
I have the same problem. After clicking outside the input the value of it disappears.

**Comment by wellington1993** [comment]
The origin of the problem is multiple calls for the datepicker method in same html element. This was my solution:

 $('.datepicker-js').datepicker({
     clearBtn: true
 });

 $( ".datepicker-js" ).removeClass( "datepicker-js");

"br is br.. always"

**Comment by chris-sun** [comment]
I also encountered this problem.  With "turbolinks" enabled and visiting a page from another page in Rails, the datepicker( ) was not appearing.  If you refresh, the page the datepicker( ) works.  But visiting from another page it didn't work.

I temporarily disabled turbolinks by adding the "data-no-turbolink" attribute to the body tag, like such:
```html
<body data-no-turbolink>
```

**Comment by Nerian** [comment]
Make sure that you are making the datepicker call inside a `page:change` handler.
```
$(document).on('page:change', function(){
 $('.datepicker').datepicker();
});
```
