### ISSUE TITLE
pick up <html lang="..."> attribute before defaulting to English

### ISSUE THREAD

**Issue by HuBandiT** [Nerian/bootstrap-datepicker-rails#108]
I would like to suggest the following language precedence order:

1. language from `data-date-language` attribute
2. language from `.datepicker()` call argument
3. language from `<html lang="...">` attribute
4. English

If the language determined by this preference list is not loaded/available, then also fall back to English.

For one case of of why/where this would be useful:

https://groups.google.com/forum/#!searchin/hobousers/datepicker/hobousers/0eBz-C9Plr8/sPevKOYust8J

**Comment by HuBandiT** [comment]
I also posted this upstream: https://github.com/eternicode/bootstrap-datepicker/issues/1552

**Comment by Nerian** [comment]
Sounds fine to me. If it gets changed in the upstream repo it will be changed here too.

**Comment by HuBandiT** [comment]
so are you saying I should leave this open as a reminder, or should I close it?

**Comment by Nerian** [comment]
You can close it now that the discussion is happening in the other repo.
