### ISSUE TITLE
Format must be set to yyyy-mm-dd by default

### ISSUE THREAD

**Issue by AlexVPopov** [Nerian/bootstrap-datepicker-rails#112]
Hello,

I was encountering a similar issue to #2. In my case the date was 2015-10-10 and the datepicker was starting at 1 November 1901. Only after I changed the `format` to `yyyy-mm-dd` did it start to work properly. I think this must be documented, as the aforementioned format is the default one for Rails. I am willing to make a PR to the README. Will you accept such a PR?

Alternatively, this option could be set in the source code, since (as already mentioned) this is the default Rails format.

**Comment by PirunSeng** [comment]
Hi,

I would say the format should be set to any in order make the date picker works properly. If the format is not set, then you might come up with the date record is not saved sometimes.

Regards,

**Comment by Nerian** [comment]
Hi,

The default settings are not set in this codebase. You may want voice your concerns in: https://github.com/eternicode/bootstrap-datepicker

**Comment by PirunSeng** [comment]
@Nerian ! I'm afraid I don't understand your statement: 'You may want voice your concerns'. I wonder if you could simply your meaning.

**Comment by Nerian** [comment]
Sure. This repository simply packages the datepicker into a gem. The actual project home is https://github.com/eternicode/bootstrap-datepicker. It's there where code changes happen, and so it's there where you should suggest the change.

**Comment by PirunSeng** [comment]
@Nerian ! Oh, I see. Sorry for my misunderstanding of reporting in wrong place.

**Comment by salmannausher** [comment]
Hello Every one
I am facing an issue if any one could help when i use date format yyyy-mm-dd it works and saves in data base perfectly but when i use other formats like mm-dd-yyyy  then it save nil ?
