### ISSUE TITLE
No route error at version 1.6.0 

### ISSUE THREAD

**Issue by kikikiblue** [Nerian/bootstrap-datepicker-rails#115]
Hi. thank you for making and maintaining this great gem. 

I met this error when I version up to 1.6.0
<pre>
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap-datepicker3.css.map")
</pre>

so I downgraded it to version 1.5.0, there is no error. 
I guess this is because https://github.com/Nerian/bootstrap-datepicker-rails/blob/master/vendor/assets/stylesheets/bootstrap-datepicker3.css#L681

Thanks.

**Comment by Nerian** [comment]
Oh looks like that line should not be there.  I updated the master branch, can you check that it works for you?

gem 'bootstrap-datepicker-rails', github: 'Nerian/bootstrap-datepicker-rails'

**Comment by kikikiblue** [comment]
It is ok now. 
Thank you for really fast response!!

**Comment by kikikiblue** [comment]
There is still a mistake in bootstrap-datepicker3.css.
I guess you delete the badline from bootstrap-datepicker.css

**Comment by Nerian** [comment]
Nice catch. Should be fixed now. And new gem has been released.
