### ISSUE TITLE
Gotchas should be in readme

### ISSUE THREAD

**Issue by garthgoldwater** [Nerian/bootstrap-datepicker-rails#119]
Since this is a wrapper for a non-rails-specific input, it might be a good idea to put some gotchas in the readme. The three I'm thinking of are

- that you have to format your strings as yyyy-mm-dd if you want rails to actually parse the dates correctly, (or install something like the american_date gem, or wire up something on your own for localization) 

- that the output in your text_field on edit forms will be formatted yyyy-mm-dd as well unless you add some logic to the text_field. 

- and that you need to set the assumeNearbyYear option for a bunch of common use-cases

Would probably reduce the number of duplicate issues you see on this project and questions on stackoverflow.

**Comment by jonjburgess** [comment]
you can actually just add.... data-date-format="yyyy/mm/dd" to the html input to format correctly and save the date without additional gems.

<input type="text" data-provide='datepicker' data-date-format='yyyy/mm/dd'>

**Comment by duaimei** [comment]
In Rails, in form_for format this worked:

<%= f.text_field :started_on, "data-provide" => 'datepicker', 'data-date-format' => 'yyyy-mm-dd' %>

**Comment by tomekr** [comment]
@duaimei how would you go about adding the nested span and glyphicon so that the `text_field` helper generates:

```html
<div class="input-group date">
  <input type="text" class="form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
</div>
```
