### ISSUE TITLE
Calendar shifted to the left

### ISSUE THREAD

**Issue by TonyDurant** [Nerian/bootstrap-datepicker-rails#121]
I've got the following issue. How can I resolve it? The calendar window shifted to the left.

<img width="555" alt="screen shot 2016-06-11 at 9 13 44 pm" src="https://cloud.githubusercontent.com/assets/1475936/15988321/ae888c1a-3019-11e6-846b-b2ff05e78b67.png">

**Comment by Nerian** [comment]
Not sure why that happens. You could use the css inspector of the browser to see what css rules are being applied to that element. You could also ask here: https://github.com/eternicode/bootstrap-datepicker
