### ISSUE TITLE
Datepicker content not being displayed

### ISSUE THREAD

**Issue by matiasgagliano** [Nerian/bootstrap-datepicker-rails#123]
![datepicker](https://cloud.githubusercontent.com/assets/7389958/17718160/c300f3b4-63e8-11e6-8360-33a8e96dff37.png)
As the picture shows, the content of the datepicker is not shown. 

The problem seems to be the rule at [line 73](https://github.com/Nerian/bootstrap-datepicker-rails/blob/master/vendor/assets/stylesheets/bootstrap-datepicker3.css#L73) in `bootstrap-datepicker3.css`. 

That very rule doesn't exist at [line 73](https://github.com/eternicode/bootstrap-datepicker/blob/master/dist/css/bootstrap-datepicker3.css#L73) in the original `bootstrap-datepicker3.css` from [eternicode/bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker).

I tried with the original source and it works just fine.

**Comment by Nerian** [comment]
I just released a new version of this gem. Try that and see if it fixes it.

**Comment by matiasgagliano** [comment]
Thanks @Nerian, everything working as expected now.
