### ISSUE TITLE
Pass date format via input attrs

### ISSUE THREAD

**Issue by kotmatpockuh** [Nerian/bootstrap-datepicker-rails#127]
<input type="text" data-provide='datepicker' >

how can i pass data format, using input attrs?

**Comment by Nerian** [comment]
I am not sure I understand the question. Please elaborate.

**Comment by kotmatpockuh** [comment]
`<input type="text" data-provide='datepicker' >`

i mean pass params (like date format) in input attrs

**Comment by Nerian** [comment]
You can find the documentation and all the options here: http://bootstrap-datepicker.readthedocs.io/en/stable/options.html?highlight=format#options

For example, format:  `data-date-format`
