### ISSUE TITLE
Datepicker startDate / endDate is not working

### ISSUE THREAD

**Issue by Deimos620** [Nerian/bootstrap-datepicker-rails#131]
I am using recent version of bootstrap-datepicker-rails (https://github.com/eternicode/bootstrap-datepicker version 1.6.4). I am trying to set startdate / enddate , not working.
Here is my code.
var startDate = "1987-07-01";
var endDate = "1991-10-06";
$(".datepicker").datepicker({
        format: 'yyyy-mm-dd',
        startDate: startDate,
        endDate: endDate
});

But this is not working for me, always keep starting from current date.
I've googled and tried several solutions , they aren't working for me.
Would you like to provide solution to help me?

**Comment by Nerian** [comment]
What's is the HTML fro that component? Is there any errors in the console? 

https://bootstrap-datepicker.readthedocs.io/en/stable/options.html#format

**Comment by Deimos620** [comment]
I don't have any error in console.
Here is html code. I've used Rails helper.
<%= f.text_field :birthday, class: 'form-control datepicker' %>
It is compiled to:
<input class="form-control datepicker" type="text" name="profile[birthday]" id="profile_birthday">

**Comment by Nerian** [comment]
Mmm, I don't why would this fail. It seems correct to me.

Try using the format 'mm/dd/yyyy' and change the data accordingly. Let's see if the datepicker is getting the data at all.

**Comment by Deimos620** [comment]
Unfortunately, It doesn't work for me.
I changed the format 'mm/dd/yyyy' , Then,  the picked date format in the input is changed correctly , but startdate / enddate is not working , too.

**Comment by Nerian** [comment]
Indeed, the demo is not working. Perhaps the version 1.7, which is what is being used in that demo,  is broken.

Personally I am using https://github.com/zpaulovics/datetimepicker-rails this in my new projects. It integrates with simpleform quite nicely.

**Comment by Deimos620** [comment]
Thanks. I will move to it.  Closing issue.
