### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by veganstraightedge** [Nerian/bootstrap-datepicker-rails#135]
Hi. Thanks for this gem. It's exactly what I need. 

I'm using Bootstrap 4 (`v4.0.0.alpha6`) in a Rails `5.1.0` app.

The calendar popup looks like it's not being styled with Bootstrap anymore. I'm guessing because v4 changed a lot of class names.

Could you add support for Bootstrap 4 please? 

Thanks!

<img width="587" alt="screen shot 2017-09-11 at 11 48 05 am" src="https://user-images.githubusercontent.com/4361/30291349-7511b372-96e7-11e7-9e03-0b652f2e5738.png">

**Comment by Nerian** [comment]
Hi,

It's not ready for B4.  Progress is being tracked here: https://github.com/uxsolutions/bootstrap-datepicker/issues/1670

**Comment by veganstraightedge** [comment]
Ok. Thanks!
