### ISSUE TITLE
Deprecation problem.

### ISSUE THREAD

**Issue by ivanelrey** [Nerian/bootstrap-datepicker-rails#137]
I get deprecation warning messages in the browser console.

DEPRECATED: The language code "kh" is deprecated and will be removed in 2.0. For Khmer support use "km" instead.

DEPRECATED: The language code "kr" is deprecated and will be removed in 2.0. For korean support use "ko" instead.

DEPRECATED: This language code "rs-latin" is deprecated (invalid serbian language code) and will be removed in 2.0. For Serbian latin support use "sr-latin" instead.

DEPRECATED: This language code "rs" is deprecated (invalid serbian language code) and will be removed in 2.0. For Serbian support use "sr" instead.

**Comment by Nerian** [comment]
Hi,

See: https://github.com/Nerian/bootstrap-datepicker-rails/issues/136
