### ISSUE TITLE
How about a release for bootstrap-datepicker 1.8.0

### ISSUE THREAD

**Issue by jesperronn** [Nerian/bootstrap-datepicker-rails#140]
https://github.com/uxsolutions/bootstrap-datepicker/commit/0d32bc5d91da11d9a3587537c3c36ce7ee815c94

It's been 7 hours since the anticipated bugfix version 1.8.0 was released. 

Who could prepare a pull request for an update?

**Comment by Nerian** [comment]
Version 1.8.0 released 🎉

**Comment by jesperronn** [comment]
:+1:
