### ISSUE TITLE
Time correction?

### ISSUE THREAD

**Issue by KemikalGeneral** [Nerian/bootstrap-datepicker-rails#142]
Hi,

I was just wondering if there's a way of either disabling the default time element of the date, or, setting it to a new one?

For example, if i chose a date, it comes with the time defaulted to 00:00:00, but can i either just have the date 2000-01-01 or, set the time manually, 2000-01-01 02:00:00

Thanks.

**Comment by Nerian** [comment]
Sure you can. The datepicker takes the value from the `val` attribute of the input.
