### ISSUE TITLE
Release for bootstrap-datepicker 1.9.0?

### ISSUE THREAD

**Issue by owst** [Nerian/bootstrap-datepicker-rails#144]
[v1.9.0](https://github.com/uxsolutions/bootstrap-datepicker/releases/tag/v1.9.0) of the underlying library was released on 2019-05-20 - please could you release a new version of this gem?

Thanks!

**Comment by simi** [comment]
Would be really nice, do you need any help @Nerian ?

**Comment by Nerian** [comment]
Hi,

I updated the assets in the repo. Please and try it and let me know if everything is okay. If so, I will publish new release.

**Comment by simi** [comment]
@Nerian everything works as expected.

**Comment by Nerian** [comment]
New release 🎈
