### ISSUE TITLE
Is there going to be a 2.0 release?

### ISSUE THREAD

**Issue by rkt739** [Nerian/bootstrap-datepicker-rails#146]
Not that 1.9 is bad, but I keep getting these deprecation warnings in the console from the localization files for deprecated language codes like `kh` and `rs`. The source files say that the deprecated localizations will be removed in 2.0. Will that perhaps happen sometime soon?

**Comment by Nerian** [comment]
Hi,

We track this code https://github.com/uxsolutions/bootstrap-datepicker and it seems 1.9 is the latest.

You can try to just include the translation that you need.

```
Instead of this:
//= require bootstrap-datepicker

Do this:
//= require bootstrap-datepicker/core
//= require bootstrap-datepicker/locales/bootstrap-datepicker.es.js
//= require bootstrap-datepicker/locales/bootstrap-datepicker.fr.js
```

**Comment by rkt739** [comment]
Thanks, that's done it

**Comment by rkt739** [comment]
Bootstrap-datepicker has now updated to 1.10. Can we get a 1.10 release for bootstrap-datepicker-rails? Thanks

**Comment by Nerian** [comment]
Sure thing. I will release a new release soon 👍

**Comment by Nerian** [comment]
1.10.0.1 released 🥳
