### ISSUE TITLE
couldn't find file 'bootstrap-datepicker'

### ISSUE THREAD

**Issue by rahuldess** [Nerian/bootstrap-datepicker-rails#70]
I did as mentioned.
## Gemfile:

gem 'bootstrap-datepicker-rails'   # For showing calender in date fields _insane_
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'devise'
gem 'carrierwave'
## application.css

 *= require jquery.Jcrop
 *= require_self
 *= require bootstrap-datepicker
 *= require_tree .
## application.js

//= require jquery
//= require jquery_ujs
//= require jquery.Jcrop
//= require bootstrap
//= require_tree .
//= require bootstrap-datepicker
## datepick.js

  $(document).ready(function(){
    $('[data-behaviour~=datepicker]').datepicker();
  });

I dint even include the .js file in my view code.. i just wanted to test whether everything is fine till now.. when i run the server ...i get below

Sprockets::FileNotFound in Users#show

Showing /home/rahul/Rails/ORIGINAL/app/views/layouts/profile.html.erb where line #13 raised:

couldn't find file 'bootstrap-datepicker'
  (in /home/rahul/Rails/ORIGINAL/app/assets/stylesheets/application.css:13)

**Comment by ladystensberg** [comment]
@prestonwrthompson I was having the same issue and your suggestion to restart the server saved me from hours of frustration! :)

**Comment by Johnfredadams** [comment]
Same problem here in an engine for rails 4.2.1. Have done the as @reggieb suggested. Works well.

**Comment by BKSpurgeon** [comment]
Same problem.

@reggieb - thank you - would you be able to elaborate on what you mean by putting "require 'bootstrap-datepicker-rails' in an initializer?

> I'd suggest putting it in an initializer.

**Comment by reggieb** [comment]
@BKSpurgeon If you are using rails, try creating an initializer `config/initializers/bootstrap-datepicker-rails.rb` with the content:

```ruby
require 'bootstrap-datepicker-rails'
```

**Comment by Nerian** [comment]
It should just get autorequired, if using Rails. Try reloading the app.
