### ISSUE TITLE
not working on Rails 4.1

### ISSUE THREAD

**Issue by xangelux** [Nerian/bootstrap-datepicker-rails#96]
I did the install (add the "gem 'bootstrap-datepicker-rails'") and call it from the coffescript on my app 

$ ->
   $('.datepicker').datepicker

It shows an error that can't find bootstrap-datepicker file. The file is not in my application directories.

**Comment by Nerian** [comment]
Did you import the javascript files as defined in https://github.com/Nerian/bootstrap-datepicker-rails#configuration ?

**Comment by xangelux** [comment]
yes, I've noticed this is a bug, I have to change the order of the imports, first has to be the bootstrap gem, then jquery and last datepicker. I doing it other way will cause problems. After doing everything, you have to reload the server, otherwise it will not find datepicker's files
