### ISSUE TITLE
newbi issue

### ISSUE THREAD

**Issue by hlms** [Nerian/bootstrap-datepicker-rails#97]
Hello all,

As mentioned on [this page](http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=yyyy%2Fmm%2Fdd&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&calendarWeeks=on&autoclose=on&todayHighlight=on&keyboardNavigation=on&forceParse=on#sandbox), I have placed the following line in html.erb page:

    <input type="text" type="text" class="form-control">

But, where should I place the following line:

    $('#sandbox-container input').datepicker({
    });

?
Thanks.

**Comment by Nerian** [comment]
Hi,

The last bit is a javascript code. You should put it inside javascript tag.

Take a look at the Test App: 

https://github.com/Nerian/bootstrap-datepicker-rails/blob/master/testapp/app/views/home/index.html.erb

**Comment by hlms** [comment]
Thanks for the link. It did help.

I used the following code in my *.html.erb to get it working in my app:



				<div class="input-daterange" data-behaviour='datepicker' id="datepicker">
					From date: <input type="text" class="input-small" name="from_date" />
					<span> to </span>
					<input type="text" class="input-small" name="to_date" />
				</div>			
 
				<script type="text/javascript">
					$('.datepicker').datepicker()
					$('[data-behaviour~=datepicker]').datepicker({
						format: "yyyy/mm/dd",
						clearBtn: true,
						calendarWeeks: true,
						autoclose: true,
						todayHighlight: true});
				</script>	

And, I was able to read it in controller through params[:from_date] and params[:to_date].
